version: '2'

services:
  rabbitmq3:
      container_name: "rabbitmq"
      image: rabbitmq:3.8-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
      ports:
          # AMQP protocol port
          - '5672:5672'
          # HTTP management UI
          - '15672:15672'
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin        
  my_vault:
    container_name: my_vault
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id roottoken
  my_vault_setup:
    image: vault:latest
    environment:
      - VAULT_ADDR=http://my_vault:8200
      - VAULT_TOKEN=roottoken
    volumes:
      - ./run.sh:/run.sh
    depends_on:
      - "my_vault"
    command: /bin/sh -c "./run.sh"
  postgresql-hackathon:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=qwerty
      - POSTGRESQL_DATABASE=hackathon_db
  postgresql-user-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=qwerty
      - POSTGRESQL_DATABASE=user_db
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-user-slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-user-master
    environment:
        - POSTGRESQL_REPLICATION_MODE=slave
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_password
        - POSTGRESQL_MASTER_HOST=postgresql-user-master
        - POSTGRESQL_PASSWORD=qwerty
        - POSTGRESQL_MASTER_PORT_NUMBER=5432
        - ALLOW_EMPTY_PASSWORD=yes
volumes:
  postgresql_master_data:
    driver: local
